### ISSUE TITLE
Using Pinecone DB as a Vector Database

### ISSUE THREAD

**Issue by TanmayDoesAI** [TanmayDoesAI/LLM-Playground#14]
### Description
Create an implementation to use the Pinecone database as the vector database to create embeddings of new documents, and store them, create a doc searcher, and use that to talk to documents.

**Comment by selamanse** [comment]
If you like #18 I'd be happy to do this one too since I am looking to gather experience with pineconedb

**Comment by TanmayDoesAI** [comment]
sure go ahead @selamanse

**Comment by selamanse** [comment]
there you go @TanmayDoesAI #19 . pinecone is fun :)

**Comment by TanmayDoesAI** [comment]
It is indeed, I'll have a look straightaway!
