### ISSUE TITLE
Create a Pull Request Template

### ISSUE THREAD

**Issue by TanmayDoesAI** [TanmayDoesAI/LLM-Playground#3]
### Description
A standardized pull request template can help contributors provide essential information about their changes. Let's create a template that prompts for details like a brief description of the changes, any related issues, and any special considerations.

### Tasks
- Create a new file named `PULL_REQUEST_TEMPLATE.md`.
- Populate the template with prompts for necessary information.
- Ensure the template is clear and concise, without any confusing elements.

### Additional Information
Feel free to refer to other repositories' Pull Request templates for inspiration and best practices. A recommended resource would be a look at the [trending repositories](https://github.com/TanmayDoesAI/LLM-Playground/issues/github.com/trending)

**Comment by frantic-rabbit** [comment]
@TanmayDoesAI, I want to work on this. Can you please assign it to me?

**Comment by TanmayDoesAI** [comment]
@frantic-rabbit Go ahead I have assigned you the issue! Thank you for contributing

**Comment by frantic-rabbit** [comment]
Hey @TanmayDoesAI, i have added the PR Template. Please have a look.
