### ISSUE TITLE
Create an Issues Template

### ISSUE THREAD

**Issue by TanmayDoesAI** [TanmayDoesAI/LLM-Playground#4]
### Description
A standardized issues template can help streamline the process of reporting bugs or suggesting enhancements. Let's create a template that prompts for details like steps to reproduce, expected behavior, and actual behavior.

### Tasks
- Create a new file named `ISSUE_TEMPLATE.md`.
- Populate the template with prompts for necessary information.
- Ensure the template is clear and user-friendly.

### Additional Information
Feel free to refer to other repositories' Issue Templates for inspiration and best practices. A recommended resource would be a look at the [trending repositories](https://github.com/TanmayDoesAI/LLM-Playground/issues/github.com/trending)

**Comment by Petsamuel** [comment]
@TanmayDoesAI Kindly Assign this to me

**Comment by TanmayDoesAI** [comment]
Go ahead @Petsamuel !! Thanks for contributing

**Comment by Petsamuel** [comment]
> Go ahead @Petsamuel !! Thanks for contributing

- For a clear and user-friendly template, I would be using YML instead of MD, and the.GitHub folder to save the templates
@TanmayDoesAI I made my PR kindly review...
