### ISSUE TITLE
Using LLMs to Summarize a YouTube Video

### ISSUE THREAD

**Issue by TanmayDoesAI** [TanmayDoesAI/LLM-Playground#7]
### Description
Create a Colab notebook that showcases how to use Large Language Models to summarize content from YouTube videos. Use existing libraries to fetch the transcript of the video and then pass it to a large language model (of your choice) and use it to summarise the transcript.

**Comment by selamanse** [comment]
Hi @TanmayDoesAI I'd like to try this one :) can you assign me please?

**Comment by TanmayDoesAI** [comment]
Go ahead @selamanse ! I have assigned this to you
